### ISSUE TITLE
kubeconfig fixture regression

### ISSUE THREAD

**Issue by alexandrem** [vapor-ware/kubetest#130]
Hello, it seems since 0.3.0 there's a regression where the previous way to override dynamically the kubeconfig path via the `kubeconfig(request)` fixture no longer works.

Example code:
```
import pytest

@pytest.fixture
def kubeconfig(request):
    return '/Users/alex/workspace/test.kubeconfig'

def test_nginx(kube):
    """An example test against an Nginx deployment."""

    kube.wait_for_ready_nodes(3, timeout=5 * 60)
```

Error message:
```
kubeconfig = '/Users/alex/workspace/test.kubeconfig', request = <SubRequest 'kube' for <Function test_nginx>>

    @pytest.fixture()
    def kube(kubeconfig, request):
        """Return a client for managing a Kubernetes cluster for testing."""
    
        if not kubeconfig:
            log.error(
                'kube fixture used when no --kube-config is set; unable to install test '
                'resources onto a cluster.'
            )
            raise errors.SetupError('--kube-config not set')
    
        test_case = manager.get_test(request.node.nodeid)
        if test_case is None:
            log.error(
                'No kubetest client found for test using the "kube" fixture. ({})'.format(
                    request.node.nodeid,
                )
            )
>           raise errors.SetupError('error generating test client')
E           kubetest.errors.SetupError: error generating test client
```

There is an example in the documentation about that, so this is confusing.

The exact same code works with 0.2.x

**Comment by edaniszewski** [comment]
thanks for opening this issue and providing good details! I'll try to look into this later today or early next week. I have some ideas as to why this may be happening, so I don't think it will take too long to identify/fix.

**Comment by edaniszewski** [comment]
I was able to reproduce based on the example code you provided. It looks like the issue is not with using a `kubeconfig` fixture override, but with a check that was added to limit test setup to only when a `--kube-config` parameter was passed as command line option.

This was done on the faulty assumption that the kubeconfig would only be set via commandline params, overlooking this method of defining the config. I'm going to try a few things out to see if I can easily add a check for this case.
